# Generated by Django 2.2.13 on 2020-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV_Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
    ]
