# Generated by Django 2.2.13 on 2020-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv_element',
            name='type_id',
            field=models.CharField(default='place_holder', max_length=200),
        ),
    ]
