# Generated by Django 2.2.13 on 2020-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_dated_entry_text_entry_titled_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dated_entry',
            name='type_id',
            field=models.CharField(default='place_holder', max_length=200),
        ),
        migrations.AddField(
            model_name='text_entry',
            name='type_id',
            field=models.CharField(default='place_holder', max_length=200),
        ),
        migrations.AddField(
            model_name='titled_entry',
            name='type_id',
            field=models.CharField(default='place_holder', max_length=200),
        ),
    ]
